In [44]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
% matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn import linear_model, datasets
from sklearn.ensemble import RandomForestClassifier

In [3]:
fifa_his=pd.read_csv('Training_fifa.csv')

In [5]:
fifa_his

year    home_team     away_team  rank_dif  rating_dif  label
0   2010       Poland     Australia       -16   13.030303      1
1   2010      Germany     Australia       -25   19.787879      0
2   2010    Australia       Denmark        14  -14.812500      0
3   2010     Portugal       Denmark        -8    3.066288      0
4   2010      Belgium       Croatia       -15    2.505682      1
5   2010      Belgium       Germany         2    1.030303      1
6   2010      Denmark       Germany        11   -4.975379      2
7   2010       Sweden       Germany        22  -12.787879      2
8   2010      England        France         6   -4.652462      1
9   2010      Germany       England       -12    5.909091      0
10  2010      Iceland      Portugal        18   -7.151515      1
11  2010      Denmark       Iceland       -10    4.085227      0
12  2010       Russia       Belgium        63   -8.418182      1
13  2014   Costa Rica        Panama       -30    3.794613      2
14  2014       Mexico        Panama       -40    5.249158      0
15  2014       Brazil        Panama       -53   11.946128      0
16  2014     Colombia       Uruguay        -1    0.272727      0
17  2014      Germany     Argentina        -4  -11.187500      0
18  2014      Germany     Argentina        -4  -11.187500      1
19  2014        Spain       Germany         7   10.212121      1
20  2014       Brazil       Germany         1   10.575758      1
21  2014  Switzerland          Peru        -5    1.331439      0
22  2014      Uruguay    Costa Rica        -8    5.090909      1
23  2014      Uruguay    Costa Rica        -8    5.090909      2
24  2014       Brazil        Serbia       -33    4.393939      0
25  2014       Brazil        Mexico       -13    6.696970      2
26  2014       Brazil      Colombia       -14    2.787879      0
27  2014    Argentina   Switzerland        -1    7.250000      0
28  2014    Argentina        Brazil         3    0.611742      1
29  2018     Portugal         Egypt       -42    4.516129      0
30  2018       Russia        France        59   -7.333333      1
31  2018      Tunisia          Iran       -22   -2.492754      0
32  2018      Belgium  Saudi Arabia       -67   -0.863636      0

In [22]:
X=fifa_his.loc[:,['rank_dif','rating_dif']]
X.shape

(33, 2)

In [21]:
y=fifa_his.loc[:,'label']
y.shape

(33,)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=205)

In [33]:
y_train.value_counts()

0    12
1    10
2     4
Name: label, dtype: int64

In [34]:
y_test.value_counts()

0    4
1    2
2    1
Name: label, dtype: int64

### train Logistic Regression

In [36]:
logreg = linear_model.LogisticRegression(C=1e5)


In [37]:
logreg.fit(X_train,y_train)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [38]:
y_pred=logreg.predict(X_test)

In [39]:
y_pred

array([0, 0, 1, 0, 0, 0, 1])

In [40]:
y_test

15    0
9     0
12    1
22    1
26    0
32    0
7     2
Name: label, dtype: int64

In [43]:
logreg.score(X_test,y_test)

0.7142857142857143

### Train Random Forest

In [48]:
clf = RandomForestClassifier(max_depth=2, random_state=0,n_estimators=100)

In [49]:
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [50]:
clf.score(X_test,y_test)

0.7142857142857143

In [62]:
clf.predict_proba([[14,-67]])

array([[0.42800251, 0.42133967, 0.15065782]])

In [61]:
clf.classes_

array([0, 1, 2])