>>># Python For Data Science

# What is Data Science

"**Data science** is an **interdisciplinary** field that uses **scientific** methods, processes, algorithms and systems to **extract knowledge and insights from data** in various forms, structured and unstructured."
*** 

<div style="text-align: right"> Wikipedia </div>
<img src="figures/DS.jpeg" />

## 1.Interdisciplinary
<img src="figures/venn.png" />

## 2. Scientific Process
<img src="figures/DSProcess.jpeg" />

## 3. Extract Insight from Structured/Unstructured Data
<img src="figures/str-vs-unstr-data.jpeg" />

# Who are your teachers? 

## Iman 

## Nima

## Florian 
- Studied Statistics at LMU Munich
- Worked as a data scientist in industry and startups

## Muzahid

## Mert 

## Hardik

# What are we going to learn in this course?

## 1. Importing and Cleaning (Preprocessing) Data 
<img src="figures/DataCleaning.jpeg" />


## 2. Eplanatory Data analysis
<img src="figures/EDA.jpeg" />

## 3. Data vizualisation
<img src="figures/fueldata.png" />

## 4. Modeling the Data
<img src="figures/DM.jpeg" />


### 4.1 Machine Leraning
<img src="figures/ML.png" />

### 4.2 Deep Learning
<img src="figures/dropout.gif" />

# What tools are we going to use?
<img src="figures/jupyter.png" style="float: left;"/><img src="pandas.png" style="float: right;"/>
<img src="figures/scikit.png" style="float: left;"/><img src="keras.png" style="float: right;"/>
<img src="figures/stackoverflow.png" style="float: left;"/>

# Example
## We are going to start with the famous IRIS dataset!
The iris dataset is a classic and very easy multi-class classification dataset.
<img src="figures/irisClasses.png"/>

|                  |   |
|------------------|---|
|classes           |3  |
|Sample per Classes|50 |
|Total Samples     |150|
|Dimentionality    |4  |
|Features          |real, Positive|





In [0]:
%matplotlib inline
import pandas as pd
import sklearn as sk
import numpy as np

In [0]:
# importing the data set
from sklearn.datasets import load_iris

# saving the data set in an object
iris = load_iris()
type(iris)

sklearn.utils.Bunch

In [0]:
# print the 4 names of the features
print(iris.feature_names)

<built-in method values of Bunch object at 0x7fe4ff77dd00>
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


# Some Machine Learning Trminology
* Each row is clled an **Observation**
* Each column is called a **Feature**
* Each value we are predicting is called **Target**


In [0]:
# Looking into the data
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

(150, 4)

In [0]:
iris.data.shape

(150, 4)

In [0]:
# print the encoded representation of the target names
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [0]:
#print the real names of the targets 0 = Setosa , 1 = Versicolor, 2 = Virginica 
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


## - Classification is a supervised Machine Learning problem in which the target is categorical.
## - Regression is a supervised Machine Learning proble in which the target is a continuoes value.
## - Clustering allows us to 
### What kind of Machine Learning problem is Iris ?

# Requirements of Scikit-Learn for working with Data
* Features and Target should be passed into scikit_Learn as **seperate objects**.
* Features and Target should be numeric.
* Features and Target should be Numpy Arrays.
* Features and Response should have specific shapes.

In [0]:
# type of target and response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [0]:
# shape of the features (first dimension= number of observations, secod dimension= number of features)
print(iris.data.shape)

(150, 4)


In [0]:
# shape of the target (single dimension matching the number of observations)
print(iris.target.shape)

(150,)


In [0]:
# store feature matrix in X
X = iris.data

# store target vector in y
y = iris.target

##  Were you able to follow and are you curious what happens next?
### Join us for the course and we will work on real-life Machine Learning Projects together

### Refrences :
* https://www.youtube.com/watch?v=6rjhrc4SEqM
* https://www.youtube.com/watch?v=hd1W4CyPX58